### ISSUE TITLE
Cortex-M specific code for disabling interrupts vs. generic critical section

### ISSUE THREAD

**Issue by MarSik** [tweedegolf/sx126x-rs#6]
Hi folks,

I am testing your code in an ESP32 based project. ESPs are based on different cores (Xtensa and Risc-V) and so the `cortex_m::asm::nop` and `cortex_m::interrupt::free` calls are not available.

Would you mind changing that to use the generic https://docs.rs/critical-section/latest/critical_section/ crate? Each user can then provide the locking implementation based on the platform.

I have the PR if you want.

**Comment by diondokter** [comment]
Hi yeah good idea! I can review your PR and merge it.
This is kind of an old crate, so it never got updated properly.

This crate was written by hdoordt, but he's no longer with our company.
So I'm still tracking down publishing rights.

**Comment by MarSik** [comment]
Well, I needed something quick for a prototype and I just stumbled on the crate. Few tweaks here and there and voila :)

The biggest custom change I have right now is support for async operation. Especially wrt the DIO1 and BUSY polling. Because both platforms and runtimes I use right now support embedded-hal-async's Wait traits.

I can post that one as well if you are interested. It maintains backwards compatibility I think :).

**Comment by diondokter** [comment]
Sound great!
